/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpfinalinventario.vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tpfinalinventario.accesoADatos.ProveedorData;
import tpfinalinventario.entidades.Proveedor;

/**
 *
 * @author santi
 */
public class ActivarProveedorView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private ProveedorData proveedorData = new ProveedorData();

    /**
     * Creates new form ActivarProveedor
     */
    public ActivarProveedorView() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
        llenarTabla();
    }

    private void armarCabeceraTabla() {

        ArrayList<Object> columns = new ArrayList();
        columns.add("RAZON SOCIAL");
        columns.add("DOMICILIO");
        columns.add("TELEFONO");

        for (Object it : columns) {
            modelo.addColumn(it);
        }

        jTableT.setModel(modelo);

    }

    public void borrarFilas() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }

    }

    private void llenarTabla() {
        borrarFilas();
        ArrayList<Proveedor> listaProveedores = null;

        listaProveedores = (ArrayList<Proveedor>) proveedorData.listaNoActivos();
        if (listaProveedores.isEmpty()) {
            return;
        }

        for (Proveedor c : listaProveedores) {
            modelo.addRow(new Object[]{c.getRazonSocial(), c.getDomicilio(), c.getTelefono()});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableT = new javax.swing.JTable();

        jButton1.setText("Activar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("LISTADO DE PROVEEDORES NO ACTIVOS");

        jTableT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = jTableT.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Tiene que seleccionar a un proveedor");
            return;
        }

        String razonSocial = (String) jTableT.getValueAt(fila, 0);
        proveedorData.activarProveedor(razonSocial);
        JOptionPane.showMessageDialog(this, "Proveedor activado exitosamente");
        llenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableT;
    // End of variables declaration//GEN-END:variables
}
