/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpfinalinventario.vistas;

import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tpfinalinventario.accesoADatos.CompraData;
import tpfinalinventario.accesoADatos.DetalleCompraData;
import tpfinalinventario.accesoADatos.ProductoData;
import tpfinalinventario.accesoADatos.ProveedorData;
import tpfinalinventario.entidades.Cliente;
import tpfinalinventario.entidades.Compra;
import tpfinalinventario.entidades.DetalleCompra;
import tpfinalinventario.entidades.DetalleVenta;
import tpfinalinventario.entidades.Producto;
import tpfinalinventario.entidades.Proveedor;
import tpfinalinventario.entidades.Venta;

/**
 *
 * @author Paula Priotti
 */
public class RealizarCompra extends javax.swing.JInternalFrame {

    ProveedorData prov = new ProveedorData();
    ProductoData prod = new ProductoData();
    CompraData compraD = new CompraData();
    DetalleCompraData dcD = new DetalleCompraData();

    /**
     * Creates new form DetalleCompraView
     */
    public RealizarCompra() {
        initComponents();
        cargarProv();
        cargarProductos();
    }

    private void cargarProv() {
        String[] columns = {"id", "nombre", "telefono"};
        DefaultTableModel mod = new DefaultTableModel(columns, 0);
        for (Proveedor p : prov.lista()) {
            Object[] d = {p.getIdProveedor(), p.getRazonSocial(), p.getTelefono()};
            mod.addRow(d);
        }
        jTableProv.setModel(mod);
    }

    private void cargarProductos() {
        String[] columns = {"id", "nombre", "categoria", "precio actual", "cantidad"};
        DefaultTableModel mod = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int i, int il) {
                return il != 4;
            }
        };
        for (Producto p : prod.lista()) {
            Object[] d = {p.getIdProducto(), p.getNombre(), p.getCategoria(), p.getPrecioActual(), "0"};
            mod.addRow(d);
        }
        jTableProd.setModel(mod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProv = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProd = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfNumCompra = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Comprar");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Proveedores");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Productos");

        jTableProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableProvMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProv);

        jTableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Ca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableProdMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProd);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Realizar compra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de compra:");

        jtfNumCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumCompraActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(jtfNumCompra)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscar)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jButtonBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jButton1))
                    .addComponent(jtfNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableProvMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProvMousePressed

    }//GEN-LAST:event_jTableProvMousePressed

    private void jTableProdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdMousePressed

    }//GEN-LAST:event_jTableProdMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //boton de realizar compra
        //metodo que obtiene cantidad de filas seleccionadas
        int cantR = jTableProv.getSelectedRowCount();
        int cantProd = jTableProd.getRowCount();
        int c = 0;
        Compra comp = new Compra();

        for (int i = 0; i < cantProd; i++) {
            if (!jTableProd.getValueAt(i, 4).equals("0")) {
                c++;
            }
        }

        if (cantR != 0 && c != 0) {
            for (int i = 0; i < cantProd; i++) {
                if (!jTableProd.getValueAt(i, 4).equals("0")) {
                    int f = jTableProv.getSelectedRow();
                    comp.setProveedor(prov.buscar((int) jTableProv.getValueAt(f, 0)));
                    comp.setFecha(LocalDate.now());
                    comp.setEstado(true);
                    compraD.guardar(comp);
                    DetalleCompra dc = new DetalleCompra();
                    Producto p = prod.buscarPorId((int) jTableProd.getValueAt(i, 0));
                    dc.setCantidad((int) jTableProd.getValueAt(i, 4));
                    dc.setPrecioCosto(p.getPrecioActual());
                    dc.setCompra(comp);
                    dc.setProducto(p);
                    dc.setEstado(true);
                    dcD.guardar(dc);
                    JOptionPane.showMessageDialog(this, "Compra realizada correctamente");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfNumCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNumCompraActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // boton buscar
        if (jtfNumCompra.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero de compra.");
            return;
        }
        int numero=0;
        try{
            numero=Integer.parseInt(jtfNumCompra.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ingrese un número.");
            return; 
        }
        
        // lista de compra, con un numero de compra, es uno solo
        Compra compra = CompraData.
        if(venta==null){
            JOptionPane.showMessageDialog(this, "No existe ese número de compra.");
            return; 
        }
           
        String fecha=venta.getFecha().toString();
        Cliente cliente=venta.getCliente();
        jLabel3.setText("Cliente: "+cliente.getNombre());
        jLabel4.setText("Fecha: "+fecha);
        // buscar en detalleVenta por idVenta
        ArrayList<DetalleVenta> listaDetalleVenta=(ArrayList<DetalleVenta>) detalleVentaData.detalleVentaPorIdVenta(venta.getIdVenta());
        
        llenarTabla(listaDetalleVenta);
        
         jLabel3.setVisible(true);
        jLabel4.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProd;
    private javax.swing.JTable jTableProv;
    private javax.swing.JTextField jtfNumCompra;
    // End of variables declaration//GEN-END:variables
}
